const {query}=require('../db/pool');
const {store,seedCatalog}=require('../db/mock');
const mock=process.env.NODE_ENV==='test'||process.env.USE_MOCK_DB==='true';
const sortPage=(rows,{page,limit})=>[...rows].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice((page-1)*limit,page*limit);
if(mock)seedCatalog();
const user={
  findByPhone:async phone=>mock?(store.users.find(u=>u.phone===phone)||null):(await query('SELECT * FROM users WHERE phone=$1',[phone])).rows[0]||null,
  findById:async id=>mock?(store.users.find(u=>u.id===id)||null):(await query('SELECT id,name,phone,role,created_at FROM users WHERE id=$1',[id])).rows[0]||null,
  create:async x=>{if(mock){const result={id:require('node:crypto').randomUUID(),name:x.name,phone:x.phone,role:'citizen',created_at:new Date().toISOString(),password_hash:x.passwordHash};store.users.push(result);const {password_hash,...safe}=result;return safe;}return(await query("INSERT INTO users(name,phone,password_hash,role) VALUES($1,$2,$3,'citizen') RETURNING id,name,phone,role,created_at",[x.name,x.phone,x.passwordHash])).rows[0];}
};
const forms={
  list:async()=>mock?store.forms.filter(x=>x.is_active):(await query('SELECT * FROM service_forms WHERE is_active=TRUE ORDER BY title')).rows,
  byKey:async key=>mock?(store.forms.find(x=>x.service_key===key&&x.is_active)||null):(await query('SELECT * FROM service_forms WHERE service_key=$1 AND is_active=TRUE',[key])).rows[0]||null
};
const schemes={list:async()=>mock?store.schemes.filter(x=>x.is_active):(await query('SELECT * FROM schemes WHERE is_active=TRUE ORDER BY name')).rows};
const submissions={
  create:async x=>{if(mock){let row=store.submissions.find(s=>s.client_uuid===x.clientUuid);const incomingAt=x.updatedAt||new Date().toISOString();if(row){row.synced_at=new Date().toISOString();if(new Date(incomingAt)>new Date(row.updated_at)){Object.assign(row,{user_id:x.userId,form_id:x.formId,data_json:x.data,updated_at:incomingAt});}return row;}row={id:require('node:crypto').randomUUID(),client_uuid:x.clientUuid,user_id:x.userId,form_id:x.formId,data_json:x.data,status:'pending',sync_status:'synced',reference_no:x.referenceNo,created_at:x.createdAt||new Date().toISOString(),updated_at:incomingAt,synced_at:new Date().toISOString()};store.submissions.push(row);return row;}return(await query(`INSERT INTO submissions(client_uuid,user_id,form_id,data_json,status,sync_status,reference_no,created_at,updated_at,synced_at) VALUES($1,$2,$3,$4,'pending','synced',$5,COALESCE($6::timestamptz,NOW()),COALESCE($7::timestamptz,NOW()),NOW()) ON CONFLICT(client_uuid) DO UPDATE SET synced_at=NOW(),user_id=CASE WHEN EXCLUDED.updated_at>submissions.updated_at THEN EXCLUDED.user_id ELSE submissions.user_id END,form_id=CASE WHEN EXCLUDED.updated_at>submissions.updated_at THEN EXCLUDED.form_id ELSE submissions.form_id END,data_json=CASE WHEN EXCLUDED.updated_at>submissions.updated_at THEN EXCLUDED.data_json ELSE submissions.data_json END,updated_at=GREATEST(submissions.updated_at,EXCLUDED.updated_at) RETURNING *`,[x.clientUuid,x.userId,x.formId,JSON.stringify(x.data),x.referenceNo,x.createdAt,x.updatedAt])).rows[0];},
  list:async a=>mock?{rows:sortPage(store.submissions.filter(s=>s.user_id===a.userId&&(!a.status||s.status===a.status)).map(s=>({...s,...{service_key:store.forms.find(f=>f.id===s.form_id)?.service_key,form_title:store.forms.find(f=>f.id===s.form_id)?.title}})),a)}:query(`SELECT s.*,f.service_key,f.title AS form_title FROM submissions s JOIN service_forms f ON f.id=s.form_id WHERE s.user_id=$1 AND ($2::text IS NULL OR s.status=$2) ORDER BY s.created_at DESC LIMIT $3 OFFSET $4`,[a.userId,a.status||null,a.limit,(a.page-1)*a.limit]),
  count:async a=>mock?store.submissions.filter(s=>s.user_id===a.userId&&(!a.status||s.status===a.status)).length:(await query('SELECT count(*)::int AS count FROM submissions WHERE user_id=$1 AND ($2::text IS NULL OR status=$2)',[a.userId,a.status||null])).rows[0].count,
  byId:async(id,userId)=>mock?(store.submissions.find(s=>s.id===id&&s.user_id===userId)||null):(await query('SELECT s.*,f.service_key,f.title AS form_title FROM submissions s JOIN service_forms f ON f.id=s.form_id WHERE s.id=$1 AND s.user_id=$2',[id,userId])).rows[0]||null
};
const grievances={
  create:async x=>{if(mock){let row=store.grievances.find(g=>g.client_uuid===x.clientUuid);const incomingAt=x.updatedAt||new Date().toISOString();if(row){row.synced_at=new Date().toISOString();if(new Date(incomingAt)>new Date(row.updated_at))Object.assign(row,{user_id:x.userId,category:x.category,description:x.description,updated_at:incomingAt});return row;}row={id:require('node:crypto').randomUUID(),client_uuid:x.clientUuid,user_id:x.userId,category:x.category,description:x.description,status:'open',reference_no:x.referenceNo,created_at:x.createdAt||new Date().toISOString(),updated_at:incomingAt,synced_at:new Date().toISOString()};store.grievances.push(row);return row;}return(await query(`INSERT INTO grievances(client_uuid,user_id,category,description,status,reference_no,created_at,updated_at,synced_at) VALUES($1,$2,$3,$4,'open',$5,COALESCE($6::timestamptz,NOW()),COALESCE($7::timestamptz,NOW()),NOW()) ON CONFLICT(client_uuid) DO UPDATE SET synced_at=NOW(),user_id=CASE WHEN EXCLUDED.updated_at>grievances.updated_at THEN EXCLUDED.user_id ELSE grievances.user_id END,category=CASE WHEN EXCLUDED.updated_at>grievances.updated_at THEN EXCLUDED.category ELSE grievances.category END,description=CASE WHEN EXCLUDED.updated_at>grievances.updated_at THEN EXCLUDED.description ELSE grievances.description END,updated_at=GREATEST(grievances.updated_at,EXCLUDED.updated_at) RETURNING *`,[x.clientUuid,x.userId,x.category,x.description,x.referenceNo,x.createdAt,x.updatedAt])).rows[0];},
  list:async a=>mock?{rows:sortPage(store.grievances.filter(g=>g.user_id===a.userId&&(!a.status||g.status===a.status)),a)}:query('SELECT * FROM grievances WHERE user_id=$1 AND ($2::text IS NULL OR status=$2) ORDER BY created_at DESC LIMIT $3 OFFSET $4',[a.userId,a.status||null,a.limit,(a.page-1)*a.limit]),
  count:async a=>mock?store.grievances.filter(g=>g.user_id===a.userId&&(!a.status||g.status===a.status)).length:(await query('SELECT count(*)::int AS count FROM grievances WHERE user_id=$1 AND ($2::text IS NULL OR status=$2)',[a.userId,a.status||null])).rows[0].count,
  byId:async(id,userId)=>mock?(store.grievances.find(g=>g.id===id&&g.user_id===userId)||null):(await query('SELECT * FROM grievances WHERE id=$1 AND user_id=$2',[id,userId])).rows[0]||null
};
module.exports={user,forms,schemes,submissions,grievances};
