const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const {randomUUID}=require('node:crypto');const repo=require('../repositories');
const httpError=(status,code,message)=>Object.assign(new Error(message),{statusCode:status,code});
const auth={register:async({name,phone,password})=>{if(await repo.user.findByPhone(phone))throw httpError(409,'PHONE_EXISTS','An account with this phone number already exists');const passwordHash=await bcrypt.hash(password,10);const user=await repo.user.create({name,phone,passwordHash});return{user,token:jwt.sign({id:user.id,name:user.name,phone:user.phone,role:user.role},process.env.JWT_SECRET,{expiresIn:'30d'})};},login:async({phone,password})=>{const user=await repo.user.findByPhone(phone);if(!user||!await bcrypt.compare(password,user.password_hash))throw httpError(401,'INVALID_CREDENTIALS','Invalid phone number or password');const safe={id:user.id,name:user.name,phone:user.phone,role:user.role};return{user:safe,token:jwt.sign(safe,process.env.JWT_SECRET,{expiresIn:'30d'})};},me:async id=>{const user=await repo.user.findById(id);if(!user)throw httpError(404,'NOT_FOUND','User not found');return user;}};
const catalog={forms:()=>repo.forms.list(),form:async key=>{const f=await repo.forms.byKey(key);if(!f)throw httpError(404,'NOT_FOUND','Service form not found');return f;},schemes:()=>repo.schemes.list()};
const itemService=kind=>({
  submit:async(userId,input)=>{const clientUuid=input.client_uuid||input.clientUuid;if(!clientUuid)throw httpError(400,'VALIDATION_ERROR','client_uuid is required');if(kind==='submissions'){let form=await repo.forms.byKey(input.service_type||input.service_key);if(!form&&typeof input.form_id==='string'&&/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(input.form_id))form={id:input.form_id};if(!form)throw httpError(400,'INVALID_FORM','A valid form_id or service_type is required');return repo.submissions.create({clientUuid,userId,formId:form.id,data:input.data_json||input.data,createdAt:input.created_at,updatedAt:input.updated_at,referenceNo:`OB-S-${randomUUID().slice(0,8).toUpperCase()}`});}return repo.grievances.create({clientUuid,userId,category:input.category||'General',description:input.description,createdAt:input.created_at,updatedAt:input.updated_at,referenceNo:`OB-G-${randomUUID().slice(0,8).toUpperCase()}`});},
  list:async(userId,page,limit,status)=>{const args={userId,page,limit,status};const [result,count]=await Promise.all([repo[kind].list(args),repo[kind].count(args)]);return{data:result.rows,meta:{page,limit,total:count,pages:Math.ceil(count/limit)}};},
  byId:async(id,userId)=>{const row=await repo[kind].byId(id,userId);if(!row)throw httpError(404,'NOT_FOUND',`${kind==='submissions'?'Submission':'Grievance'} not found`);return row;}
});
module.exports={auth,catalog,submissions:itemService('submissions'),grievances:itemService('grievances'),httpError};
